//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeLong.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeLong.Resourses.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qo&apos;shish.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manzil.
        /// </summary>
        internal static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        internal static string Adres_ {
            get {
                return ResourceManager.GetString("Adres ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Amallar {
            get {
                return ResourceManager.GetString("Amallar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank
        ///.
        /// </summary>
        internal static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijoz.
        /// </summary>
        internal static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaratilgan Vaqt.
        /// </summary>
        internal static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiqish.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiqim.
        /// </summary>
        internal static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIO.
        /// </summary>
        internal static string FIO {
            get {
                return ResourceManager.GetString("FIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma adres.
        /// </summary>
        internal static string Firma_Adres {
            get {
                return ResourceManager.GetString("Firma Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirim
        ///.
        /// </summary>
        internal static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INN.
        /// </summary>
        internal static string INN {
            get {
                return ResourceManager.GetString("INN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSHSHIR.
        /// </summary>
        internal static string JSHSHIR_ {
            get {
                return ResourceManager.GetString("JSHSHIR ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgi.
        /// </summary>
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Til.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klientni qidirish.
        /// </summary>
        internal static string MySearch {
            get {
                return ResourceManager.GetString("MySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomi.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OKONX
        ///.
        /// </summary>
        internal static string OKONX {
            get {
                return ResourceManager.GetString("OKONX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narxi Dollorda.
        /// </summary>
        internal static string Price_in_Dollars {
            get {
                return ResourceManager.GetString("Price in Dollars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narxi Sumda.
        /// </summary>
        internal static string Price_in_Sums {
            get {
                return ResourceManager.GetString("Price in Sums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mahsulot.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soni.
        /// </summary>
        internal static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qidiruv.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string Telefon {
            get {
                return ResourceManager.GetString("Telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram raqam.
        /// </summary>
        internal static string Telegram_raqam {
            get {
                return ResourceManager.GetString("Telegram raqam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jami narxi dollorda.
        /// </summary>
        internal static string Total_Price_Dollors {
            get {
                return ResourceManager.GetString("Total Price Dollors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jami narxi sumda.
        /// </summary>
        internal static string Total_Price_in_Sums {
            get {
                return ResourceManager.GetString("Total Price in Sums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yangilangan vaqt.
        /// </summary>
        internal static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ombor.
        /// </summary>
        internal static string WareHouse {
            get {
                return ResourceManager.GetString("WareHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xisob raqam.
        /// </summary>
        internal static string Xisob_raqam {
            get {
                return ResourceManager.GetString("Xisob raqam", resourceCulture);
            }
        }
    }
}
