name: .NET CI/CD

on:
  pull_request_target:
    branches: [ "deploy" ]

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build .NET App
        run: dotnet build --no-restore

  dockerize:
    name: Dockerize Backend
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PROJECT: ${{ secrets.PROJECT }}
        run: |
          docker build --platform linux/amd64 -t $DOCKER_USERNAME/$PROJECT -f ./src/backend/DeLong.WebAPI/Dockerfile .
          docker push $DOCKER_USERNAME/$PROJECT

  deploy:
    name: Deploy to AWS
    needs: dockerize
    runs-on: ubuntu-latest

    steps:
      - name: SSH into AWS Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/app
            docker-compose down
            docker-compose pull
            docker image prune -f
            docker-compose up -d
